### ISSUE TITLE
Dialog disappears randomly

### ISSUE THREAD

**Issue by MaxLeggieri** [squimer/DatePickerDialog-iOS-Swift#10]
When i open the dialog it disappear after a while, randomly, on my iPhone 5s iOS 9.0.2

**Comment by cuimingda** [comment]
me too, i guess dialog disappeared when rolate device

**Comment by serralvo** [comment]
Yes, the component is listening to  `UIDeviceOrientationDidChangeNotification`, and in the selector ` deviceOrientationDidChange` the method `close()` is called.

**Comment by lfarah** [comment]
Closing this because issue 27 is more complete
