### ISSUE TITLE
setting datepicker

### ISSUE THREAD

**Issue by ghost** [squimer/DatePickerDialog-iOS-Swift#13]
i want set minuteInterval.
but i don't access datePicker
datePicer is private property.

**Comment by benjohnde** [comment]
`datePicker` is a public variable since some commit. You can access the UIDatePicker through 

```swift
let datePickerDialog = DatePickerDialog()
let datePicker: UIDatePicker = dialogPicker.datePicker
```

Can also be closed.

Cheers!
