### ISSUE TITLE
time

### ISSUE THREAD

**Issue by DreamTekis** [squimer/DatePickerDialog-iOS-Swift#14]
How to get time from dialog?
even though mode id Time dialog returning date

**Comment by jojost1** [comment]
Like to do this as well.

**Comment by lfarah** [comment]
Hey guys, I'm the new admin of this page.
Both modes return an ```NSDate``` and in order to get the time, you have to do the following:
``` swift
let calendar = NSCalendar.currentCalendar()
let comp = calendar.components([.Hour, .Minute], fromDate: date)
let hour = comp.hour
let minute = comp.minute
```
