### ISSUE TITLE
Format date

### ISSUE THREAD

**Issue by kike0kike** [squimer/DatePickerDialog-iOS-Swift#17]
How can I format de return value? For example "dd-mm-YYYY"

Thanks!

**Comment by sha8wn** [comment]
try:

DatePickerDialog().show("Date of Birth", doneButtonTitle: "Save", cancelButtonTitle: "Cancel", datePickerMode: .Date)
        {
            (date) -> Void in
                let dateFormatter = NSDateFormatter()
                dateFormatter.dateFormat = " dd / MM / yyyy"
                self.dobTextField.text = "\(dateFormatter.stringFromDate(date))"
        }
        }
