### ISSUE TITLE
How to handle cancel button?

### ISSUE THREAD

**Issue by jgutierrez11** [squimer/DatePickerDialog-iOS-Swift#26]
When i press cancel the label showing the date resets its content.

**Comment by lfarah** [comment]
I'm working on this right now...

**Comment by lfarah** [comment]
Hey @jgutierrez11, I updated the lib.
Now on the callback you can do this:
``` swift
if date != nil {
    self.textField.text = "\(date)"
    } else {
    self.textField.text = ""
}
```
