### ISSUE TITLE
Framework file name

### ISSUE THREAD

**Issue by malhobayyeb** [squimer/DatePickerDialog-iOS-Swift#29]
After doing carthage update the framewrok file name is:

`DatePickerDialogFramework.framework`

Instead of:
`DatePickerDialog.framework`

In the `README.mdown` documentation:
You are assuming it to be: `DatePickerDialog.framework` as in: `$(SRCROOT)/Carthage/Build/iOS/DatePickerDialog.framework`

**Comment by lfarah** [comment]
Hey @malhobayyeb, thanks for spotting that! 😉
