### ISSUE TITLE
Date Picker is returning n-5 hours 

### ISSUE THREAD

**Issue by UmarJamil** [squimer/DatePickerDialog-iOS-Swift#30]
Date Picker is returning n-5 hours

**Comment by lfarah** [comment]
Hmm, interesting. I'm geting n+7 hours
<img width="358" alt="screen shot 2016-09-07 at 9 36 20 am" src="https://cloud.githubusercontent.com/assets/6511079/18320411/92847ccc-74de-11e6-87af-69d8affe5f65.png">

**Comment by lfarah** [comment]
@viniciussoares do you have any idea on how this works?

**Comment by lfarah** [comment]
I found the problem. When using NSDate, you have to use a ```NSDateFormatter``` to convert it to string:
``` swift
				let formatter = NSDateFormatter()
				formatter.dateFormat = "yyyy-MM-dd HH:mm"

				self.textField.text = "\(formatter.stringFromDate(date))"
```

**Comment by viniciussoares** [comment]
@lfarah sorry for the delayed response, i was on vacation. :sweat_smile:

**Comment by lfarah** [comment]
No problem. You deserve to rest for a bit!
