### ISSUE TITLE
Example project seems to be broken

### ISSUE THREAD

**Issue by benjohnde** [squimer/DatePickerDialog-iOS-Swift#33]
I would rather write some tests than correcting the example project.
If one has the use case to implement a date picker dialog, the readme contains enough information of how to use this project (which is pretty simple). So I recommend to just leave it out.

**Comment by lfarah** [comment]
@benjohnde I think we should do both tests and example project.

I look through 10-30 libraries a day and the easiest way to test out a library is just by running the Example project. No need to do anything but press the *play* button

**Comment by benjohnde** [comment]
True, sounds legit to me :)
