### ISSUE TITLE
Swift 3 port necessary

### ISSUE THREAD

**Issue by benjohnde** [squimer/DatePickerDialog-iOS-Swift#34]

**Comment by lfarah** [comment]
@benjohnde 
Still getting this error
<img width="817" alt="screen shot 2016-09-16 at 10 01 39 am" src="https://cloud.githubusercontent.com/assets/6511079/18594393/a34be1a4-7bf4-11e6-8b29-68b75fb6491e.png">

**Comment by benjohnde** [comment]
Check that's in your demo project, the syntax has changed. I am working on it. You will receive another PR today. The actual library is working as intended.

**Comment by benjohnde** [comment]
You may also need to set the project you are using to the latest Swift syntax.

You can achieve that by explicitly setting "Use Legacy Swift Language Version" to "No" under "Build Settings". Saying that, I assume you are using the latest Xcode 8 :)
