### ISSUE TITLE
24H format?

### ISSUE THREAD

**Issue by slown1** [squimer/DatePickerDialog-iOS-Swift#39]
Hello,

Can you please point out how to enable 24H format instead of using AM and PM for the time?

Thank you.

**Comment by lfarah** [comment]
Hey @slown1,
DatePickerDialog has a ```datePicker: UIDatePicker```, so you can select the 24H mode by doing the following:
``` swift
        let dialog = DatePickerDialog()
        dialog.datePicker.datePickerMode = UIDatePickerMode.time
        dialog.datePicker.locale = NSLocale(localeIdentifier: "en_GB") as Locale // using Great Britain for this example

        dialog.show(title: "DatePickerDialog", doneButtonTitle: "Done", cancelButtonTitle: "Cancel", minimumDate: threeMonthAgo, maximumDate: currentDate, datePickerMode: .dateAndTime) { (date) in
            if let dt = date {
                self.textField.text = "\(dt)"
            }
        }
```

Let me know if something goes wrong! 😄

**Comment by kavin06** [comment]
Thankyou so much...its working

**Comment by kavin06** [comment]
Hello,
In my project i need up to 99 hours format.how to change 24 hours to  99 hours..Can you help me

**Comment by lfarah** [comment]
@kavin06 unfortunately you won't be able to do that since UIDatePicker doesn't support that
