### ISSUE TITLE
Orientation Change forces Crash

### ISSUE THREAD

**Issue by digitaldesaster** [squimer/DatePickerDialog-iOS-Swift#4]
Hi, thanks for this tiny picker.

i wondered why my app was crashing without any messages in the log. after a while i recognized that it crashed after a orientation change. i think the NSNofiticationCenter Observer needs to be removed when the View dissapears.. As i my app is only for portrait mode i just removed the Observer.

best regards
Alex

**Comment by viniciussoares** [comment]
Sorry i didn't saw this issue, i've been very busy with my new job. 

This will be fixed this weekend along with xcode 7 support..

**Comment by viniciussoares** [comment]
aa82db6ec4e1cdee0e529b6eea4d4482a12a2068

**Comment by viniciussoares** [comment]
Donned ;) aa82db6ec4e1cdee0e529b6eea4d4482a12a2068

**Comment by viniciussoares** [comment]
Done ;) aa82db6ec4e1cdee0e529b6eea4d4482a12a2068
