### ISSUE TITLE
In ios10, the first installation of the application, not pop-up dialog

### ISSUE THREAD

**Issue by shenyufei** [squimer/DatePickerDialog-iOS-Swift#44]
Is the meaning of the title，But I quit application, then the second time, to open is no problem.

**Comment by benjohnde** [comment]
Sounds pretty weird. Maybe create a new fresh project from scratch and try out your code snippet in a clean environment.

**Comment by shenyufei** [comment]
duplicate #18 ,so close.
But this problem is not resolved. Why ?
