### ISSUE TITLE
Fails to build on Swift 2.3

### ISSUE THREAD

**Issue by Tindi** [squimer/DatePickerDialog-iOS-Swift#49]
Hi,

Great project! I have an issue building on Swift 2.3 fails with numerous errors on the DatePickerDialog.swift file. How can I build on Swift 2.3?

**Comment by smaugho** [comment]
Hi, I downgraded the source code to run in Swift 2.3. I made a pull request, but of course, the best is to create a new branch for it, to keep the support for Swift 2.3. 

While is not included in the project, you could download the DatePickerDialog.swift file directly to your project from: https://github.com/smaugho/DatePickerDialog-iOS-Swift/tree/Swift_2.3/Sources
