### ISSUE TITLE
First Responder.. / Resign 

### ISSUE THREAD

**Issue by jhoanarango** [squimer/DatePickerDialog-iOS-Swift#50]
When the textField is tapped once, it works fine, but after canceling or selecting a date, if I want to modify the date and tap on the textField, the picker does not come up again. I have to select a different textField in order for it to work again.

**Comment by lfarah** [comment]
@jhoanarango can you share a project showcasing this problem?
I'm sorry for the delay...

**Comment by dreed47** [comment]
I see the exact same behavior.  To change the date after its been set I have to tap outside my text field then back in again.

**Comment by viniciussoares** [comment]
There hasn't been any activity on this issue recently. Feel free to open a new one if you still experience this problem 👍
