### ISSUE TITLE
THE DISPLAYED DATE IS 1 LESS THAN SELECTED DATE

### ISSUE THREAD

**Issue by 7ur7Le** [squimer/DatePickerDialog-iOS-Swift#62]
If we select 4 March 2017... the displayed date will be 3 March 2017

**Comment by ameli90** [comment]
If could be because of UTC date

**Comment by 7ur7Le** [comment]
It happens if we select a date less than the current date. if we select a date which is greater than the current date, then it works fine.

**Comment by lfarah** [comment]
@7ur7Le can you show us your code?

**Comment by 7ur7Le** [comment]
@Ifarah Iam using the demo (DatePickerDialogue Example). To generate the issue, try selecting any date before the current date.
Thanks

**Comment by 7ur7Le** [comment]
Found the problem. Ameli90 was right the problem is due to UTC date.

The solution I found on stackoverflow is following :
http://stackoverflow.com/questions/27891646/xcode-in-swift-datepicker-picks-wrong-date

Thanks Amelio and Ifarah for support, closing issue.
