### ISSUE TITLE
Deprecated warning in xcode 8.3

### ISSUE THREAD

**Issue by jcrooke** [squimer/DatePickerDialog-iOS-Swift#63]
`..../Pods/DatePickerDialog/Sources/DatePickerDialog.swift:107:77: 'M_PI' is deprecated: Please use 'Double.pi' or '.pi' to get the value of correct type and avoid casting.`

**Comment by jcrooke** [comment]
Fix is in https://github.com/squimer/DatePickerDialog-iOS-Swift/pull/61

**Comment by viniciussoares** [comment]
There hasn't been any activity on this issue recently. Feel free to open a new one if you still experience this problem 👍
