### ISSUE TITLE
Unable to use

### ISSUE THREAD

**Issue by KwesiCobbina** [squimer/DatePickerDialog-iOS-Swift#69]
I get this error when i do import "cannot load underlying module for datepickerdialog". thanks in advance

**Comment by abstractapplications** [comment]
How are you adding the pod? Have you tried building the project?

**Comment by KwesiCobbina** [comment]
Fails so I'm not able to build

**Comment by benjohnde** [comment]
Seems like you used Carthage and forget about copying the framework. How did you add the module?

**Comment by viniciussoares** [comment]
There hasn't been any activity on this issue recently. Feel free to open a new one if you still experience this problem 👍
