### ISSUE TITLE
dialog not centered in landscape mode

### ISSUE THREAD

**Issue by digitaldesaster** [squimer/DatePickerDialog-iOS-Swift#8]
thanks for fixing the orientation crash. i tested your example project in the ios simulator (iPhone6, iPad Air 2). In landscape mode the dialog is not centered.

best regards
Alex

**Comment by viniciussoares** [comment]
Hello Alex,

I made some changes in the latest version. Can you test it again?

**Comment by digitaldesaster** [comment]
yes, perhaps tomorrow..

**Comment by lfarah** [comment]
Closing this because issue 27 is more complete
