### ISSUE TITLE
Support for swift 4.2

### ISSUE THREAD

**Issue by eldhoseelias** [squimer/DatePickerDialog-iOS-Swift#89]

**Comment by olidhossain23** [comment]
Same issue:
![screenshot 2018-11-02 at 10 00 38](https://user-images.githubusercontent.com/13978657/47900645-4508f900-de86-11e8-88e6-d3bcb790ca1a.png)

**Comment by veluloganathan** [comment]
use like `pod 'DatePickerDialog', :git => 'https://github.com/papipons/DatePickerDialog-iOS-Swift.git', :branch => 'swift4.2-migration'`  until https://github.com/squimer/DatePickerDialog-iOS-Swift/pull/86 get merged

**Comment by jpmcglone** [comment]
@veluloganathan that seems to be out of date now too. Does anyone have one that works?

**Comment by veluloganathan** [comment]
Out of date uh? It is working fine for me.

**Comment by viniciussoares** [comment]
Done 🎉
