### ISSUE TITLE
Support ios9 Multitasking

### ISSUE THREAD

**Issue by digitaldesaster** [squimer/DatePickerDialog-iOS-Swift#9]
In SplitView Mode on iOS9 

UIScreen.mainScreen().bounds delivers the size of the screen. But we want the size of the app. 

You can use  UIScreen.mainScreen().applicationFrame instead of UIScreen.mainScreen().bounds

btw: i think you forgot to add a listener to the cancel button ;-)

self.cancelButton.addTarget(self, action: "buttonTapped:", forControlEvents: UIControlEvents.TouchUpInside)

best regards
Alex

**Comment by viniciussoares** [comment]
Thank you Alex :D

**Comment by digitaldesaster** [comment]
Thank you for this tiny helper :-)

**Comment by digitaldesaster** [comment]
you need to replace all 
UIScreen.mainScreen().bounds
with 
UIScreen.mainScreen().applicationFrame

you still use bounds in some lines...
