### ISSUE TITLE
CocoaPods install still version 2 not 3

### ISSUE THREAD

**Issue by TristenChenTao** [squimer/DatePickerDialog-iOS-Swift#95]
CocoaPods install still version 2 not 3

**Comment by gligorkot** [comment]
@viniciussoares are you please able to push the latest podspec to the Cocoapods repo? Thanks!

**Comment by viniciussoares** [comment]
Sorry about that, i've just pushed the update. It should work now :)

https://cocoapods.org/pods/DatePickerDialog

**Comment by gligorkot** [comment]
Champion!
