### ISSUE TITLE
'UIDatePickerMode' has been renamed to 'UIDatePicker.Mode'

### ISSUE THREAD

**Issue by makslevental** [squimer/DatePickerDialog-iOS-Swift#96]
it looks like you've already fixed this [here](https://github.com/squimer/DatePickerDialog-iOS-Swift/blob/master/Sources/DatePickerDialog.swift#L27) but i just did `pod install` and got an old version? i guess you might need to publish to cocoapods?

**Comment by svguerin3** [comment]
@makslevental I'm seeing this issue as well.  I can fix locally and unlock the pod source files, but I'm not sure that fixes it for other devs working on the project.  Have you seen a fix for this, by chance?  I would really like this library, as it's exactly what we are needing.

**Comment by makslevental** [comment]
@svguerin3 put this in your Podfile instead of just the name ~> version

`  pod 'DatePickerDialog' , :git => 'ssh://git@github.com/squimer/DatePickerDialog-iOS-Swift.git'
`

it'll pull master

**Comment by svguerin3** [comment]
That worked, thank you!

**Comment by viniciussoares** [comment]
To fix this issue, just define the version on your Podfile:

```
pod 'DatePickerDialog', '~> 3.0'
```

:)
